version: '3.1'
services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    volumes:
      - ./frontend/src:/app
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '80:80'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.web
    container_name: go
    volumes:
      - ./backend/src:/app
      - backend_tmp:/app/tmp
    ports:
      - '8000:8000'
    depends_on:
      - 'db'
  cron:
    build:
      context: ./backend
      dockerfile: Dockerfile.scrape
    container_name: cron
volumes:
  node_modules:
  backend_tmp:
