FROM golang:alpine as dev

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY ./src/go.mod ./src/go.sum ./
RUN go mod download && go mod verify

COPY ./src .

CMD ["air", "-c", ".air.web.toml"]


FROM golang:alpine as builder

WORKDIR /app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY ./src/go.mod ./src/go.sum ./
RUN go mod download && go mod verify

COPY ./src .
RUN cd ./scrape && \
  CGO_ENABLED=0 go build -o /bin/scrape
RUN cd ./web && \
  CGO_ENABLED=0 go build -o /bin/web


FROM scratch as prod

COPY --from=builder /bin/web /bin/web

ENTRYPOINT ["/bin/web"]